# Replicating the demostrations and exercises from "Data Science with Jupyter" by Prateek Gupta

## Part I

In [1]:

print("Hello Python")

Hello Python


In [2]:
29+56+100+200

385

In [3]:

a = float(input())
b = float(input())
print("adding of two numbers: ", a+b)
print("difference in numbers: ", a-b)
print("multiplication of numbers: ", a*b)

2
3
adding of two numbers:  5.0
difference in numbers:  -1.0
multiplication of numbers:  6.0


In [4]:
# writing an empty list in python
height = []
type(height)

list

In [5]:
# a list containing heights
height_list = [1.76, 1.64, 1.79, 1, 57, 88]
print(height_list)

[1.76, 1.64, 1.79, 1, 57, 88]


In [6]:
# a list containing str and float
height_list = ["Tom",1.76, "Harry", 1.64, "Lisa", 1.79,"Mona", 1.57, "John"]
print(height_list)

['Tom', 1.76, 'Harry', 1.64, 'Lisa', 1.79, 'Mona', 1.57, 'John']


In [7]:
lang = ['python', 'C', 'java']
print(lang[0] + ' is very easy to learn for data science')
print(lang[1] + ' is the first language I have learnt')
print(lang[2] + ' is difficult to learn for data science')

python is very easy to learn for data science
C is the first language I have learnt
java is difficult to learn for data science


In [8]:
lang[2] = 'cobol'
print(lang)

['python', 'C', 'cobol']


In [9]:
language_list = ['python', 'C', 'cobol']
for language in language_list:
    print("language is: ", language)

language is:  python
language is:  C
language is:  cobol


In [10]:
# checking how many elements are there 
language_list = ['python', 'C', 'cobol']
print("elements in the list: ", len(language_list))

elements in the list:  3


In [11]:
# adding a new language
language_list.append("java")
print(language_list)

['python', 'C', 'cobol', 'java']


In [12]:
language_list.insert(3, ".net")
print(language_list)

['python', 'C', 'cobol', '.net', 'java']


In [13]:
language_list.remove('java')
print(language_list)

['python', 'C', 'cobol', '.net']


In [14]:
language_list.remove(".net")
print(language_list)

['python', 'C', 'cobol']


In [15]:

language_list.pop(1)
print(language_list)

['python', 'cobol']


In [16]:
number_list = [1, 2, 3, 4, 1]
number_list.remove(4)
print(number_list)

[1, 2, 3, 1]


In [17]:
number_list = [1, 2, 3, 4, 1]
number_list.pop(0)
print(number_list)

[2, 3, 4, 1]


In [18]:
number_list = [1, 2, 3, 4, 1]
del(number_list[4])
print(number_list)

[1, 2, 3, 4]


In [19]:
language_list = ['python', 'C', '.net', 'cobol', 'java']
language_list.sort()
print(language_list)

['.net', 'C', 'cobol', 'java', 'python']


In [20]:
language_list.sort(reverse=True)
print(language_list)

['python', 'java', 'cobol', 'C', '.net']


In [21]:
dict_example = {
    'brand' : 'Hyundai',
    'model' : 'Creta' ,
    'type' : 'SUV' , 
    'year' : '2017'
}
print(dict_example)

{'brand': 'Hyundai', 'model': 'Creta', 'type': 'SUV', 'year': '2017'}


In [22]:
car_brand_by_key = dict_example ['brand']
print(car_brand_by_key)

Hyundai


In [23]:
dict_example.get('brand')

'Hyundai'

In [24]:
dict_example['year'] = 2018
print(dict_example)

{'brand': 'Hyundai', 'model': 'Creta', 'type': 'SUV', 'year': 2018}


In [25]:
for car_property in dict_example:
    print('key in dict:', car_property)

key in dict: brand
key in dict: model
key in dict: type
key in dict: year


In [26]:
for car_property_value in dict_example.values():
    print('value', car_property_value)

value Hyundai
value Creta
value SUV
value 2018


In [27]:
for car_property, car_property in dict_example.items():
    print(car_property, car_property_value)

Hyundai 2018
Creta 2018
SUV 2018
2018 2018


In [28]:
import math

In [29]:
# define area as variable area
area = 0
# define radius as variable r
r = 5.89
# calculate area
area = math.pi*r**2
print("area of land is: ", area)

area of land is:  108.98844649760245


In [30]:
# defining my own function
def my_function():
    print('Hello world')
my_function()

Hello world


In [31]:
# defining a function to return sum of two numbers
def add_two_numbers(a,b):
    return a+b
add_two_numbers(10,8)

18

In [32]:
# defining a function with default parameter
def add_function(a,b=6):
    return a + b
# call add_function() with only a parameter
add_function(a=2)

8

In [33]:
# define add_function() function to accept any no. of parameters
def add_function(*apcs):
    return sum(apcs)
# calculate the sum of numbers
add_function(9, 4, 8, 10)

31

In [34]:
# define a global scope variable
my_text = "I am learning Python for data science"

def first_function():
    """This function uses global scope variable"""
    print(my_text)
first_function()

def second_function():
    """This function also uses global scope variable"""
    print(my_text)
second_function()

I am learning Python for data science
I am learning Python for data science


In [35]:
def my_function():
    #print(my_text)
    my_text = "I am also learning  hahohi"
    print(my_text)

my_text = "I am learning Python"
my_function()
print(my_text)

I am also learning  hahohi
I am learning Python


In [36]:
multiply = lambda x: x*5
multiply(2)

10

In [37]:
sum = lambda x, y: (x-y)*x*y
sum(9,8)

72

# NumPy Foundation

In [38]:
# importing numpy package
import numpy as np

In [39]:

distance = [55, 60, 45]
speed = [6, 10, 7]
dist = np.array(distance)
spd = np.array(speed)
time = dist/spd
print(time)

[9.16666667 6.         6.42857143]


In [40]:
# data type
print("data type of array:", time.dtype)
# no. of dimesions
print("no. of dimesions:", time.ndim)
# size of each dimension
print("size of each dimension:", time.shape)
# total size of array
print("total size of array:", time.size)

data type of array: float64
no. of dimesions: 1
size of each dimension: (3,)
total size of array: 3


In [41]:
# writing arrays with random variables
np.random.seed(0) # seed for reproductivity
x1 = np.random.randint(10, size=6) # one-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # two-dimensional array
x3 = np.random.randint(10, size=(3,4,5)) # three-dimensional array

print('x1 ndim: ', x1.ndim)
print('x1 shape: ', x1.shape)
print('x1 size: ', x1.size)

print('x2 ndim: ', x2.ndim)
print('x2 shape: ', x2.shape)
print('x2 size: ', x2.size)

print('x3 ndim: ', x3.ndim)
print('x3 shape: ', x3.shape)
print('x3 size: ', x3.size)

x1 ndim:  1
x1 shape:  (6,)
x1 size:  6
x2 ndim:  2
x2 shape:  (3, 4)
x2 size:  12
x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [42]:
f = np.arange(0, 20, 5)
print('sequential array with steps of 5:\n', f)

sequential array with steps of 5:
 [ 0  5 10 15]


In [43]:
print('1-d array:', x1)
print('second element of the first array:', x1[1])
print('last element of the first array:', x1[-6])
print('first element of the first array:', x1[0])

1-d array: [5 0 3 3 7 9]
second element of the first array: 0
last element of the first array: 5
first element of the first array: 5


In [44]:
print('2-d array:', x2)
print('3-d array:', x3)

2-d array: [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3-d array: [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [45]:
# make an array
x = np.arange(10)
print('our array:' ,x)
print('first five elements:', x[:5])
print('elements after index 5:', x[5:])
print('middle sub-array:', x[4:7])
print('every other element', x[::2])
print('every other element starting at index 1:' , x[1::2])
print('elements in reversed order:', x[::-1])

our array: [0 1 2 3 4 5 6 7 8 9]
first five elements: [0 1 2 3 4]
elements after index 5: [5 6 7 8 9]
middle sub-array: [4 5 6]
every other element [0 2 4 6 8]
every other element starting at index 1: [1 3 5 7 9]
elements in reversed order: [9 8 7 6 5 4 3 2 1 0]


In [46]:
print('2-d array:\n' , x2)
print('two rows, three columns:\n', x2[:2, :2])

2-d array:
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
two rows, three columns:
 [[3 5]
 [7 6]]


In [47]:
# original array
print('original
      ; 2-d array:\n', x2)

SyntaxError: EOL while scanning string literal (<ipython-input-47-e63f17689061>, line 2)

In [48]:
x2_sub = x2[:3, :2]
print(x2_sub)

[[3 5]
 [7 6]
 [1 6]]


In [49]:
x2_sub[0, 0] = 88
print(x2_sub)

[[88  5]
 [ 7  6]
 [ 1  6]]


In [50]:
print(x2)

[[88  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [51]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[88  5]
 [ 7  6]]


In [52]:
x2_sub_copy[0, 0] = 42
print("copied array after changes:\n", x2_sub_copy)
print("original array:\n", x2)

copied array after changes:
 [[42  5]
 [ 7  6]]
original array:
 [[88  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [53]:
#### ARRAY CONCATENATION
# merging two arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
# combining both arrays using concatenate
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [54]:
# writing a sample array
x = np.array([1, 2, 3])
# writing 2-d array
grid = np.array([[9, 8, 7],
               [6, 5, 4]])
# vertically stack the array
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [55]:
# horizontally stack the arrays
y = np.array([[99],
             [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Pandas and Dataframe

### Series

In [56]:
# importing Pandas package using alias
import pandas as pd

In [57]:
# writing an empty series

x = pd.Series()
print('empty series: ', x)

empty series:  Series([], dtype: float64)


<ipython-input-57-24e7a4b65413>:3: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  x = pd.Series()


In [58]:
# series example
series1= pd.Series([10, 20, 30, 50])
print(series1)

0    10
1    20
2    30
3    50
dtype: int64


In [59]:
# re-indexing the default index column
series1 = pd.Series([10, 20, 30, 50], index=['a', 'b', 'c', 'd'])
print(series1)

a    10
b    20
c    30
d    50
dtype: int64


In [60]:
# accessing a series element
series1['d']

50

In [61]:
# data manipulation with Series
print('adding 5 to the series:\n' , series1 + 7)


adding 5 to the series:
 a    17
b    27
c    37
d    57
dtype: int64


In [62]:
print('filtering a series with greated than 30:\n' , series1[series1 > 30])

filtering a series with greated than 30:
 d    50
dtype: int64


In [63]:
import numpy as np

In [64]:
print('square root of Series elements:\n' , np.sqrt(series1))

square root of Series elements:
 a    3.162278
b    4.472136
c    5.477226
d    7.071068
dtype: float64


In [65]:
# a sample dictionary
data = {'abc' : 1, 'def' : 2, 'ghi' : 3}
print('dictionary exmaple: \n' , data)

dictionary exmaple: 
 {'abc': 1, 'def': 2, 'ghi': 3}


In [66]:
pd.Series(data)

abc    1
def    2
ghi    3
dtype: int64

## Dataframe

In [67]:
# writing an empty dataframe
df = pd.DataFrame()
print('dataframe example:\n', df)

dataframe example:
 Empty DataFrame
Columns: []
Index: []


In [68]:
# a sample list containing name and age
data = [['Tom', 10], ['Harry', 12], ['Jim', 13]]
# writing a dataframe from a given list  with column names
df = pd.DataFrame(data, columns = ['Names', 'Age'])
df

Names  Age
0    Tom   10
1  Harry   12
2    Jim   13

In [69]:
# accessing a dataframe column - first way
df['Names']

0      Tom
1    Harry
2      Jim
Name: Names, dtype: object

In [70]:
# accessing a dataframe column - second way
df.Names

0      Tom
1    Harry
2      Jim
Name: Names, dtype: object

In [71]:
# adding a column in existing dataframes
df['Year'] = 2008
df

Names  Age  Year
0    Tom   10  2008
1  Harry   12  2008
2    Jim   13  2008

In [72]:
print('original dataframe:\n', df)
del df['Year']
print('dataframe after del:\n', df)
df.pop('Age')
print('dataframe after pop:\n', df)

original dataframe:
    Names  Age  Year
0    Tom   10  2008
1  Harry   12  2008
2    Jim   13  2008
dataframe after del:
    Names  Age
0    Tom   10
1  Harry   12
2    Jim   13
dataframe after pop:
    Names
0    Tom
1  Harry
2    Jim


In [73]:
# a sample dataframe containing stock data
data = pd.DataFrame({'price':[95, 25, 85, 41],
                    'ticker':['AXP', 'CISCO', 'DIS', 'MSFT'],
                    'company':['American Express', 'Cisco', 'Walt Disney', 'Microsoft']})
data

price ticker           company
0     95    AXP  American Express
1     25  CISCO             Cisco
2     85    DIS       Walt Disney
3     41   MSFT         Microsoft

In [74]:
# access the value that is at index 0, in column 'company' using loc
print(data.loc[0]['ticker'])

AXP


In [75]:
# access the value that is at index 0, in column 'company' using iloc
print(data.iloc[0][2])

American Express


In [76]:
# inspecting top 2 rows of a dataframe
print('top 2 data:\n', data.head(2))

top 2 data:
    price ticker           company
0     95    AXP  American Express
1     25  CISCO             Cisco


In [77]:

# inspecting below 2 rows of a dataframe
print('below 2 data:\n', data.tail(2))

below 2 data:
    price ticker      company
2     85    DIS  Walt Disney
3     41   MSFT    Microsoft


In [78]:
# check data types of columns
data.dtypes

price       int64
ticker     object
company    object
dtype: object

In [79]:
# descriptive statistics of the data
data.describe()

price
count   4.000000
mean   61.500000
std    33.798422
min    25.000000
25%    37.000000
50%    63.000000
75%    87.500000
max    95.000000

In [80]:
# information of the dataframe
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   price    4 non-null      int64 
 1   ticker   4 non-null      object
 2   company  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes


### Handling missing values in DataFrames

In [81]:
import numpy as np
# a sample datframe
df = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f', 'h'],
                 columns=['one', 'two', 'three'])
# writing a data with missing values by reindexing
df2 = df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
df2


one       two     three
a  1.254414  1.419102 -0.743856
b       NaN       NaN       NaN
c -2.517437 -1.507096  1.149076
d       NaN       NaN       NaN
e -1.193578  1.141042  1.509445
f  1.067775 -0.686589  0.014873
g       NaN       NaN       NaN
h -0.375666 -0.038224  0.367974

In [82]:
# checking missing values using isnull()
print(df2.isnull())

     one    two  three
a  False  False  False
b   True   True   True
c  False  False  False
d   True   True   True
e  False  False  False
f  False  False  False
g   True   True   True
h  False  False  False


In [83]:
missing_values_count = df2.isnull().sum()
print('count of missing values:\n', missing_values_count)

count of missing values:
 one      3
two      3
three    3
dtype: int64


In [84]:
# remove all the rows that contain a missing value
df2 = df2.dropna()
df2

one       two     three
a  1.254414  1.419102 -0.743856
c -2.517437 -1.507096  1.149076
e -1.193578  1.141042  1.509445
f  1.067775 -0.686589  0.014873
h -0.375666 -0.038224  0.367974

In [85]:
df2

one       two     three
a  1.254414  1.419102 -0.743856
c -2.517437 -1.507096  1.149076
e -1.193578  1.141042  1.509445
f  1.067775 -0.686589  0.014873
h -0.375666 -0.038224  0.367974

In [86]:
# filling NaN with zeros
df3 = df2.fillna(0)
df3

one       two     three
a  1.254414  1.419102 -0.743856
c -2.517437 -1.507096  1.149076
e -1.193578  1.141042  1.509445
f  1.067775 -0.686589  0.014873
h -0.375666 -0.038224  0.367974

In [87]:
# replace all NA's the value that comes directly after it in the same column
# then replace all the remaining na's with 0
df4 = df2.fillna(method = 'bfill', axis = 0).fillna(0)
df4

one       two     three
a  1.254414  1.419102 -0.743856
c -2.517437 -1.507096  1.149076
e -1.193578  1.141042  1.509445
f  1.067775 -0.686589  0.014873
h -0.375666 -0.038224  0.367974

## Interacting with Databases with SQLALchemy

In [88]:
import pandas as pd

In [89]:
import sqlalchemy as db
from sqlalchemy import create_engine

In [90]:
### engine = db.create_engine('mysql://root:1984@127.0.0.1:3306/rms_dev')
engine = create_engine("mysql://root:1984@127.0.0.1:3306/rms_dev")

In [ ]:
connection = engine.connect()

In [ ]:
# Inserting A Table In a Database
query = "CREATE TABLE customers (name VARCHAR(225), address VARCHAR(255))"
connection.execute(query)
print("Table Name:", engine.table_names())
connection.close()

In [ ]:
engine = db.create_engine('mysql://root:1984@127.0.0.1:3306/rms_dev')
connection = engine.connect()
sql = "INSERT INTO customers (name, address) VALUES ('Prateek', 'India')"
connection.execute(sql)
connection.close()

In [ ]:
# Inserting Data In a Table
engine = db.create_engine('mysql://root:1984@127.0.0.1:3306/rms_dev')
connection = engine.connect()
sql = "SELECT * from customers"
result = connection.execute(sql)
print('table data:' , result.fetchall())
connection.close()

In [ ]:
# update a record
engine = db.create_engine('mysql://root:1984@127.0.0.1:3306/rms_dev')
connection = engine.connect()
sql = "UPDATE customers SET address = 'Singapore' WHERE address = 'India'"
connection.execute(sql)
print ("record(s) is updated")
q = 'SELECT * from customers'
result = connection.execute(q)
print('table data:' , result.fetchall())
connection.close()

In [ ]:
# Deleting a record
engine = db.create_engine('mysql://root:1984@127.0.0.1:3306/rms_dev')
connection = engine.connect()
sql = "DELETE FROM customers WHERE address = 'Singapore'"
connection.execute(sql)
print("record is deleted")
connection.close()

In [ ]:
#inner join two tables
engine = db.create_engine('mysql://root:1984@127.0.0.1:3306/rms_dev')
connection = engine.connect()
query = "CREATE TABLE IF NOT EXISTS users (id INT , name VARCHAR(255), prod_id INT)"
connection.execute(query)
sql = "INSERT INTO users (id, name, prod_id) VALUES (1, 'Prateek', 11),(2, 'John', 12),(3, 'Tom', 13)"
connection.execute(sql)
query2 = "CREATE TABLE IF NOT EXISTS products (id INT, name VARCHAR(255))"
connection.execute(query2)
sq12 = "INSERT INTO products (id, name) VALUES (11, 'Apple'),(12, 'Samsung'),(13, 'Vivo')"
connection.execute(sq12)
connection.close()

In [ ]:
engine = db.create_engine('mysql://root:1984@127.0.0.1:3306/rms_dev')
connection = engine.connect()
join_query = "SELECT \
  users.name AS user, \
  products.name AS favorite \
  FROM users \
  INNER JOIN products ON users.prod_id = products.id"
result = connection.execute(join_query)
myresult = result.fetchall()
for bought_product in myresult:
    print(bought_product)

In [ ]:
# Left joim
engine = db.create_engine('mysql://root:1984@127.0.0.1:3306/rms_dev')
connection = engine.connect()
left_join = "SELECT \
    users.name AS user, \
    products.name AS favorite \
    FROM users \
    Left JOIN products ON users.prod_id = products.id"
result = connection.execute(left_join)
myresult = result.fetchall()
for bought_product in myresult:
    print(bought_product)



## Thinking Statistically in Data Science


In [ ]:
# mean
import pandas as pd
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(np.mean(a))
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))



In [ ]:
# median
a = np.array([[10, 7, 4], [3, 2, 1]])
print(np.median(a))
print(np.median(a, axis=0))
print(np.median(a, axis=1))

In [ ]:
from scipy import stats
a = np.array([[1, 3, 4, 2, 2, 7],
             [5, 2, 2, 1, 4, 1],
             [3, 3, 2, 2, 1, 1]])
m = stats.mode(a)
print(m[0])

In [ ]:

from scipy.stats import poisson
import matplotlib.pyplot as plt
plt.title("Probability Distribution Example")
arr = []
rv = poisson(25)
# rv is Poissson discrete random variable
# pmf is probability mass fuction which is a fuction that can predict mathmatical probability

for num in range(0, 40):
    arr.append(rv.pmf(num))
prob = rv.pmf(28)
plt.grid(True)
plt.plot(arr, linewidth=2.0)
plt.plot([28], [prob], marker='None', markersize=6, color='red')# None instead of 0
plt.show()

In [ ]:
from scipy.stats import binom
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1)
x = range(7)
n, p = 6, 0.5
rv = binom(n, p)
ax.vlines(x, 0, rv.pmf(x), colors = 'k', linestyles='-', lw=1,label='Probability of success')
ax.legend(loc='best', frameon=False)
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

range = np.arange(-3, 3, 0.001)
plt.plot(range, norm.pdf(range, 0, 1))
plt.show()

In [ ]:
# Probability Density Function
from scipy.stats import norm
import numpy as np
import matplotlib.pyplot as plt
x = np.arange(-4, 4, 0.001)
plt.plot(x, norm.pdf(x))
plt.show()

In [ ]:
# Pearson Correlation Coefficient
import scipy
from scipy.stats import pearsonr
x = scipy.array([-0.65499887, 2.34644428, 3.0])
y = scipy.array([-1.46049758, 3.86537321, 21.0])
r_row, p_value = pearsonr(x, y)
print(r_row) # r_row denotes Pearson's correlation coefficient
print(p_value) # p_value denotes the probability of zn uncorrelated system.....

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# array containing no of total experience
dss_exp = np.array([12, 15, 13, 20, 19, 20, 11, 19, 11, 12, 19, 13, 12, 10, 6, 19, 3, 1, 1, 0, 4, 4, 6, 5, 3, 7, 12, 7, 9, 8, 12,
                   11, 11, 18, 19, 18, 19, 3, 6, 5, 6, 9, 11, 10, 14, 14, 16, 17, 17, 19, 0, 2, 0, 3, 1, 4, 6, 6, 8, 7, 7, 6, 7,
                   11, 11, 10, 11, 10, 13, 13, 15, 18, 20, 19, 1, 10, 8, 16, 19, 19, 17, 16, 11, 1, 10, 13, 15, 3, 8, 6, 9, 10, 
                   15, 19, 2, 4, 5, 6, 9, 11, 10, 9, 10, 9, 15, 16, 18, 13])

# undestanding the underlying distribution of experience
# plot the distribution of experience
plt.hist(dss_exp, range = (0,20), bins = 21)

#add axis labels
plt.xlabel("Experience in Years")
plt.ylabel("Frequency")
plt.title("Distribution of Experience in Data Science Specialization")
# draw the red vertical line in graph at the average experience
plt.axvline(x=dss_exp.mean(), linewidth=2, color = 'r')
plt.show()
# statistics of DSS Batch experience
print("Mean Experience of DSS Batch: {:4.3f}".format(dss_exp.mean()))
print("Std Deviation of Experience of DSS Batch: {:4.3f}".format(dss_exp.std()))


In [ ]:
# page 91
import numpy as np
# set the parameters for sampling
n = 10
NUM_TRIALS = 1000
# Estimating DSS Experience from samples
samp = np.random.choice(dss_exp, size = n, replace = True)#Just try for 1 iteration
samp_mean = samp.mean()
samp_sd = samp.std()
print('Samp_mean = {:4.3f} Sample_SD = {:4.3f}'.format(samp_mean, samp_sd))
print("sample values:", samp)


In [ ]:
#How will the distribution of sample mean look like
import numpy as np

np.random.seed(100)
mn_array = np.zeros(NUM_TRIALS)
sd_array = np.zeros(NUM_TRIALS)

# Extract random samples and compute mean & standard deviation
for i in range(NUM_TRIALS):
    samp = np.random.choice(dss_exp, size = n, replace = True)
    mn_array[i] = samp.mean()

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
mn = mn_array.mean()
sd = mn_array.std()
x5_pct = np.percentile(mn_array, 5.0)
x95_pct = np.percentile(mn_array, 95.0)
print('Mean = {:4.3f}, std Dev = {:4.3f}, 5% Pct = {:4.3f}, 95% Pct = {:4.3f}'.format(mn, sd, x5_pct, x95_pct))
# plot sampling distribution by meqn
plt.hist(mn_array, range =(0,20), bins = 41)
# add sxis labels
plt.xlabel("Avg Experience with n={}".format(n))
plt.ylabel("Frequency")
plt.title("Sampling Distribution of Mean")
plt.axvline(x=x5_pct, linewidth=2, color='r')
plt.axvline(x=x95_pct, linewidth=2, color='r')
plt.show()

## How to import data in Python?

In [ ]:
import pandas as pd
crime_data = pd.read_csv(r"C:\Users\husni\Desktop\data Science with jupyter\Crimes_-_2001_to_Present.csv")

In [ ]:
crime_data.head()

In [ ]:
import pandas as pd
order_data = pd.read_excel(r"C:\Users\husni\Desktop\data Science with jupyter\Sample - Superstore.xls", sheet_name="Orders")
order_data.head()

In [ ]:
import pandas as pd
import json
glossary_data = pd.read_json(r'C:\Users\husni\Desktop\data Science with jupyter\glossary.json', orient = 'table')

In [ ]:
# unzipping nfl zip data
import zipfile
Dataset = "NFL Play by Play 2009-2017 (v4).csv.zip"
with zipfile.ZipFile("C:\Users\husni\Desktop\data Science with jupyter"+Dataset, "r") as z:
    z.extractall("C:\Users\husni\Desktop\data Science with jupyter\Dataset")

In [ ]:
# import required modules
import pandas as pd
import numpy as np

# reading NFL data
nfl_data = pd.read_csv(r"C:\Users\husni\Desktop\data Science with jupyter\NFL Play by Play 2009-2017 (v4).csv", low_memory=False)
building_permits = pd.read_csv(r"C:\Users\husni\Desktop\data Science with jupyter\Building_Permits.csv", low_memory=False)

In [ ]:
# looking up the data
nfl_data.sample(5)


In [ ]:
building_permits.sample(5)

In [ ]:
# getting the number of missing values per column
missing_values_count = nfl_data.isnull().sum()
# looking at the first 10 columns missing values in nfl dataset
missing_values_count[0:10]



In [ ]:
# how many total missing values do we have in nfl_data
total_cells = np.prod(nfl_data.shape)
total_missing = missing_values_count.sum()
print(total_cells)
print(total_missing)
# percent of data that is missing
(total_missing/total_cells)*100

In [ ]:
# getting the number of missing values per column Building permits
missing_permits_count = building_permits.isnull().sum()
# looking at the first 10 columns missing values in building permits dataset
missing_permits_count[0:10]


In [ ]:
# how many total missing values do we have in nfl_data
total_cells_permits = np.prod(building_permits.shape)
total_missing_permits = missing_permits_count.sum()
# percent of data that is missing
(total_missing_permits/total_cells_permits)*100

In [ ]:
# remove all columns with at least one missing one value
columns_with_na_dropped = nfl_data.dropna(axis=1)
columns_with_na_dropped.head()

# checking how much data did we lose?
print("Columns in original dataset:", nfl_data.shape[1])
print("Columns with missing values dropped:", columns_with_na_dropped.shape[1])

In [ ]:
# remove all rows with at least one missing value
rows_with_na_dropped = building_permits.dropna(axis=0)
rows_with_na_dropped.head()

# checking how much data did we lose?
print("Rows in original dataset:", building_permits.shape[1])
print("Rows with missing values dropped:", rows_with_na_dropped.shape[1])

In [ ]:
# get a small subsetof nfl dataset
subset_nfl_data = nfl_data.loc[:, 'EPA':'Season'].head()
subset_nfl_data

# replace all NA's with 0
subset_nfl_data.fillna(0)

In [ ]:
# replace all NaN's the value that comes directly after it in the same column
# then replace all the remaining NaN's with 0
subset_nfl_data.fillna(method= 'bfill', axis=0).fillna(0)

In [ ]:
# get a small subsetof building permits dataset
subset_building_permits = building_permits.loc[:, 'Street Number Suffix':'Site Permit'].head()
subset_building_permits

# replace all NA's with 0
subset_building_permits.fillna(0)

In [ ]:
# replace all NaN's the value that comes directly after it in the same column
# then replace all the remaining NaN's with 0
subset_building_permits.fillna(method= 'bfill', axis=0).fillna(0)

In [ ]:
import pandas as pd
import numpy as np

# for box-Cox Transformation
from scipy import stats

# for min_max scaling 
from mlxtend.preprocessing import minmax_scaling

# for visualization
import seaborn as sns
import matplotlib.pyplot as plt

# reading kickstarters projects
kickstarters_2017 = pd.read_csv(r"C:\Users\husni\Desktop\data Science with jupyter\ks-projects-201801.csv", engine = "python")
# set seed for reproductivity
np.random.seed(0)
kickstarters_2017.head()

In [ ]:
kickstarters_2017.columns

In [ ]:
# select the usd_goal_real_column
usd_goal = kickstarters_2017.usd_goal_real

# scale the goals from 0 to 1
scaled_data = minmax_scaling(usd_goal, columns = [0])

# plot the original & scaled data together to compare
fig, ax = plt.subplots(1, 2)
sns.distplot( kickstarters_2017.usd_goal_real, ax = ax[0])
ax[0].set_title("original Data")
sns.distplot(scaled_data, ax = ax[1])
ax[1].set_title("Scaled data")
plt.show()

In [ ]:
# get the index of all positive pledges (Box -Cox only takes positive values)
index_of_positive_pledges = kickstarters_2017.usd_pledged_real > 0

# get only positive pledges (using their indexes)
positive_pledges = kickstarters_2017.usd_pledged_real.loc[index_of_positive_pledges]

# normalize the pledges (w/ Box-Cox)
normalized_pledges = stats.boxcox(positive_pledges)[0]

# plot both together to compare
fig, ax = plt.subplots(1, 2)
sns.distplot(positive_pledges, ax = ax[0])
ax[0].set_title("original Data")
sns.distplot(normalized_pledges, ax = ax[1])
ax[1].set_title("Normalized data")
plt.show()

In [ ]:
# get the index of all positive pledges (Box -Cox only takes positive values)
index_of_positive_pledges = kickstarters_2017.pledged > 0

# get only positive pledges (using their indexes)
positive_pledges = kickstarters_2017.pledged.loc[index_of_positive_pledges]

# normalize the pledges (w/ Box-Cox)
normalized_pledges = stats.boxcox(positive_pledges)[0]

# plot both together to compare
fig, ax = plt.subplots(1, 2)
sns.distplot(positive_pledges, ax = ax[0])
ax[0].set_title("original Data")
sns.distplot(normalized_pledges, ax = ax[1])
ax[1].set_title("Normalized data")
plt.show()

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import datetime

# read in our data
earthquakes = pd.read_csv(r"C:\Users\husni\Desktop\data Science with jupyter\database.csv")
landslides = pd.read_csv(r"C:\Users\husni\Desktop\data Science with jupyter\catalog.csv")
volcanos = pd.read_csv(r"C:\Users\husni\Desktop\data Science with jupyter\database.csv")

# set seed reproductivity
np.random.seed()

landslides.head()

In [ ]:
landslides.info()

In [ ]:
# do a new column, date_parsed, wth the parsed dates
landslides['date_parsed'] = pd.to_datetime(landslides['date'], format = "%m/%d/%y")
# print the first few rows
landslides['date_parsed'].head()


In [ ]:
# get the day of the month from the date_parded column
day_of_month_landslides = landslides['date_parsed'].dt.day
day_of_month_landslides

In [ ]:
volcanos.head()


In [ ]:
volcanos.info()


In [ ]:
# try to read in a file not in UTF-8
kickstarter_2016 = pd.read_csv(r'C:\Users\husni\Desktop\data Science with jupyter\ks-projects-201612.csv')


In [ ]:
# helpful character encoding module
import chardet

# look at the first ten thousand bytes to guess the character encoding
with open(r'C:\Users\husni\Desktop\data Science with jupyter\ks-projects-201801.csv', 'rb') as rawdata:
    result = chardet.detect(rawdata.read(10000))

# check what the character encoding might be
print(result)


In [ ]:
# read in the file with encoding detected by chardet
kickstarter_2016 = pd.read_csv(r'C:\Users\husni\Desktop\data Science with jupyter\ks-projects-201612.csv',
                              encoding = 'Windows-1252', low_memory=False)

# look at the first few lines
kickstarter_2016.head(2)


In [ ]:
# read in our data
suicide_attacks = pd.read_csv(r'C:\Users\husni\Desktop\data Science with jupyter\PakistanSuicideAttacks Ver 11 (30-November-2017).csv',
                              encoding = 'Windows-1252')
suicide_attacks.head()


In [ ]:
# get all the unique values in the 'city' column
cities = suicide_attacks['City'].unique()

In [ ]:
# sort them alphabetically and the take a closer look
cities.sort()
cities

In [ ]:
# convert to lower case
suicide_attacks['City'] = suicide_attacks['City'].str.lower()
# remove trailing white spaces
suicide_attacks['City'] = suicide_attacks['City'].str.strip()

In [ ]:
cities

In [ ]:
import zipfile
with zipfile.ZipFile(r"C:\Users\husni\Desktop\data Science with jupyter\winemag-data_first150k.csv.zip") as z:
    z.extractall(r"C:\Users\husni\Desktop\data Science with jupyter")  

In [ ]:
import pandas as pd
reviews_df = pd.read_csv(r"C:\Users\husni\Desktop\data Science with jupyter\winemag-data_first150k.csv", index_col = 0)
reviews_df.head(5)


In [ ]:
import matplotlib.pyplot as plt
reviews_df['province'].value_counts().head(10).plot.bar()
plt.xlabel('Province')
plt.ylabel("No of Wines")
plt.title('Province with Wine Production Data')
plt.show()


In [ ]:
import matplotlib.pyplot as plt
reviews_df['points'].value_counts().sort_index().plot.line()
plt.xlabel('points')
plt.ylabel('No of wines')
plt.title('points with Wine Production Data')
plt.show()


In [ ]:
reviews_df[reviews_df['price'] < 200]['price'].plot.hist()
plt.show()

In [ ]:
reviews_df[reviews_df['price'] > 200]['price'].plot.hist()
plt.show()


In [ ]:
reviews_df[reviews_df['price'] < 100].sample(100).plot.scatter(x = 'price', y = 'points')
plt.show()

In [ ]:
wine_count_df = pd.read_csv(r"C:\Users\husni\Desktop\data Science with jupyter\top-five-wine-score-counts.csv", index_col = 0)
wine_count_df.head()

In [ ]:
wine_count_df.plot.bar(stacked = True)
plt.show()

In [ ]:
import pandas as pd
cancer_df = pd.read_csv(r"C:\Users\husni\Desktop\data Science with jupyter\breast_cancer.csv")
cancer_df.head(10)


In [ ]:
import seaborn as sns
malignant_tumour = cancer_df[cancer_df['diagnosis'] == 'M']['area_mean']
benign_tumour = cancer_df[cancer_df['diagnosis'] == 'B']['area_mean']
sns.boxplot(x = 'diagnosis', y = 'area_mean', data = cancer_df)
plt.savefig(r'C:\Users\husni\Desktop\data Science with jupyter\cancer_area_mean_diagnosis.png')
plt.show()